import = ["~/.config/alacritty/kanagawa/kanagawa-wave.toml"]

[window]
decorations = "Buttonless"
padding = {x = 16, y = 16}
opacity = 0.85
blur = false

[font]
normal = { family = "monospace", style = "Regular"}
size = 10

[mouse]
hide_when_typing = true
